name: Build base sysbox

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.8.9"

      - uses: actions/checkout@v4
      
      - name: Build base sysbox
        run: |
          earthly --platform=linux/amd64 --ci --use-inline-cache --save-inline-cache --push +base-sysbox --registry ${{ env.REGISTRY }}/${{ github.repository_owner }}

  build-arm64:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "0.8.9"
          
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - uses: actions/checkout@v4
      
      - name: Build base sysbox
        run: |
          earthly --platform=linux/arm64 --ci --use-inline-cache --save-inline-cache --push +base-sysbox --registry ${{ env.REGISTRY }}/${{ github.repository_owner }}

  merge-platforms:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create and push multi-arch manifest
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ github.repository_owner }}/base-sysbox"
          docker buildx imagetools create -t $IMAGE:latest \
            $IMAGE:$GITHUB_SHA-amd64 \
            $IMAGE:$GITHUB_SHA-arm64
